<a href="https://colab.research.google.com/github/RKR01997/Social_Network_Ads-Classification-/blob/main/Social_Network_Ads(Classification)__LR_%26DT_%26_RF_%26_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Social_Network_Ads ML Exercise

1) Read the dataset 'Social_Network_Ads.csv'<br>
2) Remove/handle null values<br>
3) Considering 'Age' and 'Estimated Salary' as input features and 'Purchased' as output feature, generate the following models after splitting the dataset into training and test dataset with test_size as 25%.<br>
a) Logistic Regression <br>
b) Decision Tree <br>
c) RandomForest <br>
d) KNN<br>
and predict the Purchased class label.<br>
4) Generate confusion matrix and classification report for each of these models.<br> 
5) Compute Accuracy score for each of these models.<br>
6) Scale the input features using feature Scaling and then repeat question 3, 4 and 5<br>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/Social_Network_Ads.csv')

In [ ]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
df['Gender']=le.fit_transform(df['Gender'])

In [ ]:
df.shape

(400, 5)

In [ ]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)

**Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression

mod=LogisticRegression()
mod.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
print(mod.score(x_test,y_test))
mod_pred=mod.predict(x_test)
print(mod_pred[:5])

0.77
[0 0 0 1 0]


In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print(confusion_matrix(y_test,mod_pred))
print(classification_report(y_test,mod_pred))

[[63  2]
 [21 14]]
              precision    recall  f1-score   support

           0       0.75      0.97      0.85        65
           1       0.88      0.40      0.55        35

    accuracy                           0.77       100
   macro avg       0.81      0.68      0.70       100
weighted avg       0.79      0.77      0.74       100



**Decision** **Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

mod2=DecisionTreeClassifier()
mod2.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
print(mod2.score(x_test,y_test))
mod2_pred=mod2.predict(x_test)
print(mod2_pred[:5])

0.83
[1 0 0 1 1]


In [ ]:
print(confusion_matrix(y_test,mod2_pred))
print(classification_report(y_test,mod2_pred))

[[56  9]
 [ 8 27]]
              precision    recall  f1-score   support

           0       0.88      0.86      0.87        65
           1       0.75      0.77      0.76        35

    accuracy                           0.83       100
   macro avg       0.81      0.82      0.81       100
weighted avg       0.83      0.83      0.83       100



**Random Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

mod3=RandomForestClassifier()
mod3.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
print(mod3.score(x_test,y_test))
mod3_pred=mod3.predict(x_test)
print(mod3_pred[:5])

0.88
[1 0 0 1 1]


In [ ]:
print(confusion_matrix(y_test,mod3_pred))
print(classification_report(y_test,mod3_pred))

[[58  7]
 [ 5 30]]
              precision    recall  f1-score   support

           0       0.92      0.89      0.91        65
           1       0.81      0.86      0.83        35

    accuracy                           0.88       100
   macro avg       0.87      0.87      0.87       100
weighted avg       0.88      0.88      0.88       100



**K-nearest Neighbors**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

mod4=KNeighborsClassifier()
mod4.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
print(mod4.score(x_test,y_test))
mod4_pred=mod4.predict(x_test)
print(mod4_pred[:5])

0.77
[0 0 0 1 0]


In [ ]:
print(confusion_matrix(y_test,mod4_pred))
print(classification_report(y_test,mod4_pred))

[[59  6]
 [17 18]]
              precision    recall  f1-score   support

           0       0.78      0.91      0.84        65
           1       0.75      0.51      0.61        35

    accuracy                           0.77       100
   macro avg       0.76      0.71      0.72       100
weighted avg       0.77      0.77      0.76       100



***Upscaling Using HyperPerimeteric tuning***

In [ ]:
from sklearn.model_selection import cross_val_score

**Decision Tree**

In [ ]:
criterion=['gini','entropy']

for i in criterion:
  score=cross_val_score(DecisionTreeClassifier(criterion=i),x,y)
  print(f'At {i},accuracy is {score.mean()}')
  print('At',i,",accuracy score is",score.mean())

At gini,accuracy is 0.805
At gini ,accuracy score is 0.805
At entropy,accuracy is 0.8150000000000001
At entropy ,accuracy score is 0.8150000000000001


In [ ]:
for i in range(3,20):
  score=cross_val_score(DecisionTreeClassifier(min_samples_split=i),x,y)
  print(f'At min_samples_split {i},accuracy score is {score.mean()}')

At min_samples_split 3,accuracy score is 0.8075000000000001
At min_samples_split 4,accuracy score is 0.8125
At min_samples_split 5,accuracy score is 0.8075000000000001
At min_samples_split 6,accuracy score is 0.7949999999999999
At min_samples_split 7,accuracy score is 0.7925000000000001
At min_samples_split 8,accuracy score is 0.7875
At min_samples_split 9,accuracy score is 0.79
At min_samples_split 10,accuracy score is 0.7949999999999999
At min_samples_split 11,accuracy score is 0.795
At min_samples_split 12,accuracy score is 0.8
At min_samples_split 13,accuracy score is 0.8025
At min_samples_split 14,accuracy score is 0.7875
At min_samples_split 15,accuracy score is 0.7725
At min_samples_split 16,accuracy score is 0.7725
At min_samples_split 17,accuracy score is 0.7725
At min_samples_split 18,accuracy score is 0.795
At min_samples_split 19,accuracy score is 0.795


In [ ]:
for i in range(5,20):
  score=cross_val_score(DecisionTreeClassifier(max_depth=i),x,y)
  print(f'At max_depth {i},accuracy score is {score.mean()}')

At max_depth 5,accuracy score is 0.8074999999999999
At max_depth 6,accuracy score is 0.795
At max_depth 7,accuracy score is 0.8099999999999999
At max_depth 8,accuracy score is 0.8225
At max_depth 9,accuracy score is 0.8
At max_depth 10,accuracy score is 0.8125
At max_depth 11,accuracy score is 0.8200000000000001
At max_depth 12,accuracy score is 0.8099999999999999
At max_depth 13,accuracy score is 0.8
At max_depth 14,accuracy score is 0.8099999999999999
At max_depth 15,accuracy score is 0.8174999999999999
At max_depth 16,accuracy score is 0.8174999999999999
At max_depth 17,accuracy score is 0.8099999999999999
At max_depth 18,accuracy score is 0.8074999999999999
At max_depth 19,accuracy score is 0.8025


In [ ]:
cv1=DecisionTreeClassifier(criterion='gini',max_depth=8,min_samples_split=4)
cv1.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=8, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=4,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
print(cv1.score(x_test,y_test))
cv1_pred=cv1.predict(x_test)
print(cv1_pred[:5])

0.81
[1 0 0 1 1]


In [ ]:
print(confusion_matrix(y_test,cv1_pred))
print(classification_report(y_test,cv1_pred))

[[55 10]
 [ 9 26]]
              precision    recall  f1-score   support

           0       0.86      0.85      0.85        65
           1       0.72      0.74      0.73        35

    accuracy                           0.81       100
   macro avg       0.79      0.79      0.79       100
weighted avg       0.81      0.81      0.81       100



**Random Forest**

In [ ]:
for i in range(10,100,5):
  n=cross_val_score(RandomForestClassifier(n_estimators=i),x,y)
  print(f'At n equals to {i},accuracy score is {score.mean()}')

At n equals to 10,accuracy score is 0.795
At n equals to 15,accuracy score is 0.795
At n equals to 20,accuracy score is 0.795
At n equals to 25,accuracy score is 0.795
At n equals to 30,accuracy score is 0.795
At n equals to 35,accuracy score is 0.795
At n equals to 40,accuracy score is 0.795
At n equals to 45,accuracy score is 0.795
At n equals to 50,accuracy score is 0.795
At n equals to 55,accuracy score is 0.795
At n equals to 60,accuracy score is 0.795
At n equals to 65,accuracy score is 0.795
At n equals to 70,accuracy score is 0.795
At n equals to 75,accuracy score is 0.795
At n equals to 80,accuracy score is 0.795
At n equals to 85,accuracy score is 0.795
At n equals to 90,accuracy score is 0.795
At n equals to 95,accuracy score is 0.795


In [ ]:
for i  in range (5,20):
  md=cross_val_score(RandomForestClassifier(max_depth=i),x,y)
  mss=cross_val_score(RandomForestClassifier(min_samples_split=i),x,y)
  print(f'At max_depth {i},accuracy score is {md.mean()}')
  print(f'At min_samples_split {i},accuracy score is {mss.mean()}')

At max_depth 5,accuracy score is 0.875
At min_samples_split 5,accuracy score is 0.8724999999999999
At max_depth 6,accuracy score is 0.8749999999999998
At min_samples_split 6,accuracy score is 0.8725000000000002
At max_depth 7,accuracy score is 0.8674999999999999
At min_samples_split 7,accuracy score is 0.875
At max_depth 8,accuracy score is 0.8674999999999999
At min_samples_split 8,accuracy score is 0.8724999999999999
At max_depth 9,accuracy score is 0.8675
At min_samples_split 9,accuracy score is 0.875
At max_depth 10,accuracy score is 0.8724999999999999
At min_samples_split 10,accuracy score is 0.8775000000000001
At max_depth 11,accuracy score is 0.8699999999999999
At min_samples_split 11,accuracy score is 0.8825
At max_depth 12,accuracy score is 0.8699999999999999
At min_samples_split 12,accuracy score is 0.8774999999999998
At max_depth 13,accuracy score is 0.8649999999999999
At min_samples_split 13,accuracy score is 0.8774999999999998
At max_depth 14,accuracy score is 0.8675
At min

In [ ]:
bootstrap=[True,False]

for i in bootstrap:
  score=cross_val_score(RandomForestClassifier(bootstrap=i),x,y)
  print('At',i,'accuracy score is',score.mean())

At True accuracy score is 0.8724999999999999
At False accuracy score is 0.8549999999999999


In [ ]:
cv2=RandomForestClassifier(criterion='gini',n_estimators=70,max_depth=5,min_samples_split=19,bootstrap=True)
cv2.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=19,
                       min_weight_fraction_leaf=0.0, n_estimators=70,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
print(cv2.score(x_test,y_test))
cv2_pred=cv2.predict(x_test)
print(cv2_pred[:5])

0.88
[1 0 0 1 1]


In [ ]:
print(confusion_matrix(y_test,cv2_pred))
print(classification_report(y_test,cv2_pred))

[[58  7]
 [ 5 30]]
              precision    recall  f1-score   support

           0       0.92      0.89      0.91        65
           1       0.81      0.86      0.83        35

    accuracy                           0.88       100
   macro avg       0.87      0.87      0.87       100
weighted avg       0.88      0.88      0.88       100



**K-nearest Neighbors**

In [ ]:
for i in range(3,20):
  score=cross_val_score(KNeighborsClassifier(n_neighbors=i),x,y)
  print(f'At n {i},accuracy score is {score.mean()}')

At n 3,accuracy score is 0.7074999999999999
At n 4,accuracy score is 0.7275
At n 5,accuracy score is 0.7275
At n 6,accuracy score is 0.7475
At n 7,accuracy score is 0.74
At n 8,accuracy score is 0.755
At n 9,accuracy score is 0.755
At n 10,accuracy score is 0.755
At n 11,accuracy score is 0.75
At n 12,accuracy score is 0.7525
At n 13,accuracy score is 0.7525000000000001
At n 14,accuracy score is 0.7424999999999999
At n 15,accuracy score is 0.7424999999999999
At n 16,accuracy score is 0.7450000000000001
At n 17,accuracy score is 0.7425
At n 18,accuracy score is 0.7450000000000001
At n 19,accuracy score is 0.7474999999999999


In [ ]:
cv3=KNeighborsClassifier(n_neighbors=10)
cv3.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [ ]:
print(cv3.score(x_test,y_test))
cv3_pred=cv3.predict(x_test)
print(cv3_pred[:5])

0.76
[0 0 0 1 0]


In [ ]:
print(confusion_matrix(y_test,cv3_pred))
print(classification_report(y_test,cv3_pred))

[[62  3]
 [21 14]]
              precision    recall  f1-score   support

           0       0.75      0.95      0.84        65
           1       0.82      0.40      0.54        35

    accuracy                           0.76       100
   macro avg       0.79      0.68      0.69       100
weighted avg       0.77      0.76      0.73       100

